name: build
on:
  pull_request:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
            
    steps:
      - name: my first step
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Robert
          MIDDLE_NAME: Iron
          LAST_NAME: STARK
        run: echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
        
      - name: my second step
        if: success()
        run: echo "The previous step has finished sucessfully"
      
      - name: my third step
        uses: actions/checkout@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          
      - name: my fourth step
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: 'Message that will be displayed on users first issue'
          pr-message: 'message that will displayed on users pr'
